### ISSUE TITLE
Redraw only one window

### ISSUE THREAD

**Issue by jucacrispim** [jonathanslenders/python-prompt-toolkit#115]
Hi.

I have a layout with two window inside a HSplit. In the bottom window I have an input and in the upper window I'm displaying the output with a TokenListControl. Is there a way to redraw only one window when the user submit some data?

Thanks.

**Comment by jonathanslenders** [comment]
Hi @jucacrispim 

I'm sorry for the late reply, I was on holiday.
Are you asking for a feature or an optimization?

Currently the renderer already takes the difference between the current output and the previous output. So, if only the bottom pane has some changes, the output of the upper pane is not sent to the terminal.
However, the ``get_tokens`` function of ``TokenListControl`` is still called to render the output in memory.

Are you experiencing high CPU?

Jonathan

**Comment by jucacrispim** [comment]
@jonathanslenders I wrote a simple example that I think explains better what I'm trying to say. https://gist.github.com/jucacrispim/5008b406820e62e7541c

The problem is that everytime I enter some data or just press <enter> all windows are redrawn. In one of my experiments I have tried a 'full screen' cli and I saw this redraw as a blink. Maybe it's related to  the blinking issue?

Trying to figure how that works I saw that all children of a HSplit write_to_screen() everytime. Changing somethings to make it not call write_to_screen() everytime I saw that instead of the 'old' window content I had a blank window. I didn't went further to investigate where the things were erased, but maybe somewhere in my code I'm erasing it without realize?

And I'm not experiencing high CPU, or nothing that I have noticed, probably I'm just misunderstanding how something works.

Thanks.

**Comment by jonathanslenders** [comment]
Hi @jucacrispim  Can you tell me what operating system you are using, and which version of Python. (also 32 or 64 bit.)

I tried your script lately and it seemed to work. Now I updated it to the latest version of the master branch of prompt_toolkit: https://gist.github.com/jonathanslenders/29d6e19904cd0364455f  and it still works fine.

It could indeed be that it's related to the blinking issue. A few people see things blink in their terminal, and I haven't figured out yet how to fix that. (I can't reproduce it yet.)

Hopefully, I find a solution soon.
Jonathan

**Comment by jucacrispim** [comment]
Hi @jonathanslenders 

Python version is 3.4.2
Operating system is Debian GNU/Linux  8 (jessie) 64 bits.

**Comment by jonathanslenders** [comment]
And which terminal application?

**Comment by jucacrispim** [comment]
Oh, I'm sorry.

I'm using Konsole (KDE's terminal emulator)

**Comment by jonathanslenders** [comment]
Hi @jucacrispim,

Sorry for the late reply. I think now I get what you mean. It's not a terminal bug.

The problem is that calling ``cli.run()`` will run the user interface until output is returned. (by pressing enter.) At that point it will write the whole interface to stdout and flush that. In the next iteration of the loop, a new interface is drawn.

What you probably have to do is pass a custom ``accept_action`` to the default buffer. This way you can do other things instead of returning the result. E.g. change the content of the other window.
See: https://github.com/jonathanslenders/python-prompt-toolkit/blob/c1170c9b72eec9f1b57fd96a515dc2609bacfda6/prompt_toolkit/buffer.py#L35

See here a modified version of your application:
https://gist.github.com/jonathanslenders/9fa44c0f2108047b9c66

I hope it helps (and it's not too much too late.)
Jonathan
