### ISSUE TITLE
History doesn't work

### ISSUE THREAD

**Issue by Tyilo** [jonathanslenders/python-prompt-toolkit#124]
Code:

```
from __future__ import unicode_literals
from prompt_toolkit.shortcuts import get_input
from prompt_toolkit.history import History

def main():
    history = History()

    while True:
        text = get_input("> ", history=history)
        print('You entered:', text)
    print('GoodBye!')

if __name__ == '__main__':
    main()
```

Entering `foo` and then pressing the up-arrow does nothing. This happens in both Python 2.7.9 and 3.4.2 on OS X 10.10.3.

**Comment by Tyilo** [comment]
The problem is that the string isn't added to the history with `history.append`. You should probably fix [the tutorial](https://github.com/jonathanslenders/python-prompt-toolkit/tree/master/examples/tutorial).

**Comment by gvangool** [comment]
@Tyilo the `history.append` is called in [`Buffer.append_to_history`](https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/prompt_toolkit/buffer.py#L870-L882)

**Comment by Tyilo** [comment]
@gvangool So you're saying that it should work? Because I have to call `history.append` manually.

`FileHistory` works without calling `append` manually.

**Comment by gvangool** [comment]
I just stepped through it with pdb and I see the call to `append_to_history` and the subsequent call to [`History.append`](https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/prompt_toolkit/history.py#L16). But I also notice that the next run through `get_input` you have an empty history.

**Comment by jonathanslenders** [comment]
Hi all, this is indeed a bug. Thanks for helping!

The problem is at this line:
https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/prompt_toolkit/history.py#L22
When the history is still empty ``__len__`` returns zero.

Then at this line:
https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/prompt_toolkit/shortcuts.py#L242
we do a fallback to a default History() class if the first item has a non-true value.

A history instance with zero length evaluates to ``False``, so we replace that with a new instance. The next call of ``get_input`` we replace the old history instance again, which is still zero and it gets replaced again.

The solution is probably to implement a ``__bool__`` for history. (and ``__nonzero__`` for Python 2). I'll fix it asap.

Jonathan

**Comment by jonathanslenders** [comment]
Fixed in: https://github.com/jonathanslenders/python-prompt-toolkit/commit/24d4f8155174830e42b390864b2c70eb7ae61c84

**Comment by Tyilo** [comment]
Thanks!
