### ISSUE TITLE
Stop get_input from another thread

### ISSUE THREAD

**Issue by Tyilo** [jonathanslenders/python-prompt-toolkit#125]
I want `get_input` to raise an exception, when some global flag `SHOULD_STOP` is set to `True` (by another thread). Is there an easy way of doing this?

I think I would have to rewrite both the posix and win32 eventloop to support this, but that doesn't seem like a very good way.

**Comment by jonathanslenders** [comment]
Hi @Tyilo,

That is possible and it shouldn't be hard.

Have a look at the implementation of ``get_input`` first: https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/prompt_toolkit/shortcuts.py#L253
You will need to copy paste the code inside this function, because you need access to the ``CommandLineInterface`` object called ``cli``.

Then it is possible to set a return value from another thread:
```python
def set_return():
    cli.set_return_value(None)

cli.eventloop.call_from_thread(set_return)
```
Using ``call_from_thread`` is necessary because it will make sure that the event loop in the main thread unblocks and that if there is already something running in the main thread, that the execution of this function is suspended until that part is finished. So, no locking required.

Does that work? (I didn't test it.)
Jonathan

**Comment by Tyilo** [comment]
Thanks, it seems to work, however it's called `call_from_executor` instead of `call_from_thread`.

**Comment by jonathanslenders** [comment]
Oh, yes. That was what I meant. Glad it worked!
