### ISSUE TITLE
ControlQ key binding has no effect

### ISSUE THREAD

**Issue by itamargal** [jonathanslenders/python-prompt-toolkit#136]
I'm playing around with the [custom key binding example](https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/examples/custom-key-binding.py). I've added the following key binding to the main loop:

    @key_bindings_manager.registry.add_binding(Keys.ControlQ)
    def quit(event):
        event.cli.set_return_value(None)

When I run the example and press Ctrl-Q, nothing happens. However when I replace ControlQ with e.g. ControlA or ControlB, it seems to work.

**Comment by jonathanslenders** [comment]
What happens when you run ``stty -ixon`` in your bash shell before starting your application?

Both Control-S and Control-Q are by default used for flow control in vt100 terminals. As far as I understand, it means that the application running in the terminal will never receive any of these two key strokes. By running ``stty -ixon`` you disable flow control and that should work again.

**Comment by pablopalacios** [comment]
I got the same issue here. Adding `stty -ixon` worked. Is This not a case to add another example within docs? Or maybe to add a note for this?
