### ISSUE TITLE
ImportError: cannot import name 'create_cli'

### ISSUE THREAD

**Issue by scopatz** [jonathanslenders/python-prompt-toolkit#141]
Some of our [xonsh](https://github.com/scopatz/xonsh) users have noticed that the `prompt_toolkit` is no longer working with recent versions of the code.  In particular, it looks like the `create_cli()` function is now gone.  See scopatz/xonsh#324.  The trace back that we are seeing is:

```console
$ SHELL_TYPE=prompt_toolkit xonsh
Traceback (most recent call last):
  File "/usr/bin/xonsh", line 3, in <module>
    main()
  File "/usr/lib/python3.4/site-packages/xonsh/main.py", line 58, in main
    shell = Shell(**shell_kwargs)
  File "/usr/lib/python3.4/site-packages/xonsh/shell.py", line 37, in __init__
    from xonsh.prompt_toolkit_shell import PromptToolkitShell
  File "/usr/lib/python3.4/site-packages/xonsh/prompt_toolkit_shell.py", line 6, in <module>
    from prompt_toolkit.shortcuts import create_cli, create_eventloop
ImportError: cannot import name 'create_cli'
```

Would it be possible to add this function back in, perhaps even as a compatibility layer for deprecated functionality? If not, what should this be replaced with?

**Comment by scopatz** [comment]
Thanks in advance!

**Comment by jonathanslenders** [comment]
Hi @scopatz,

Yes, in order to separate the I/O backends (like local, SSH, telnet, etc...) from the application logic we had to refactor some things.

The most high-level, easy to call function is the "get_input" function.

See the pull request that I created: https://github.com/scopatz/xonsh/pull/334
This fixes also another issue with the "get_prompt_tokens" function that returned a list where a string was expected.

One thing to be done for better integration with ``xonsh`` is support for colors. You are using ANSI escape codes. prompt_toolkit by design doesn't work with ANSI codes, because that makes some assumptions about the terminal/console on which it runs. Windows consoles don't support that. So, we expect instead ``get_prompt_tokens`` to return a list of (Token, text) tuples, similar to what the Pygments lexer returns. A Token is a Pygments token that can be assigned a color. It's the render engine later on that turns the color into the escape code or correct system call for the terminal.

**Comment by jonathanslenders** [comment]
One other import thing is that ``get_prompt_tokens`` is called every time the prompt is rendered, so on every single key press. (The reason for this is that a prompt can be dynamic and change as you type.) Xonsh is calling ``format_prompt_for_prompt_toolkit`` every time, and that is actually slow.

Either, calculate the prompt once, right before calling ``get_input`` and give it a function that returns the calculated result, or make it faster.

**Comment by scopatz** [comment]
Thanks for the feedback and the PR @jonathanslenders.  @anula will probably be interested in this.

**Comment by jonathanslenders** [comment]
Also have a look at this example: https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/examples/colored-prompt.py

![colored-prompt](https://cloud.githubusercontent.com/assets/216638/9026811/cbe44e12-393d-11e5-85c1-b0dce9e79c4d.png)

**Comment by scopatz** [comment]
Thanks @jonathanslenders!
