### ISSUE TITLE
Integration of finalterm/iterm2 escape sequences for shell integration.

### ISSUE THREAD

**Issue by jonathanslenders** [jonathanslenders/python-prompt-toolkit#148]
Have a look at following escape sequences: before_prompt, after_prompt, before_output, after_output:

https://groups.google.com/forum/#!msg/iterm2-discuss/URKCBtS0228/rs5Ive4PCAAJ
https://iterm2.com/shell_integration.html
https://github.com/asmeurer/iterm2-tools/blob/master/iterm2_tools/shell_integration.py

See: https://github.com/ipython/ipython/issues/8724

**Comment by asmeurer** [comment]
See also https://iterm2-tools.readthedocs.io/en/latest/shell_integration.html

**Comment by asmeurer** [comment]
It would be neat if prompt_toolkit supported this directly. Then I wouldn't have to have separate implementations for IPython and xonsh.  It's also complicated for IPython, where I have to use some special hooks to get the "before output" sequences to display after the user input but before any output is shown. For xonsh, I would have to [add some hooks](https://github.com/scopatz/xonsh/issues/374#issuecomment-148934197).

**Comment by Carreau** [comment]
May possible to make a specific Token type, like `Tokan.raw` that would forward the sequences unchanged ? So that you might not have to special case `before_prompt`, `after_prompt`, `before_output`, `after_output` and user could inject them whenever the like ?

**Comment by jonathanslenders** [comment]
It's more complex then this.

The hard thing is that render engine will position everything from such a token list in a 2 dimensional grid. (after doing some transformations, scrolling text, etc..) Output is then rendered by taking the previous in-memory grid and doing a "diff" operation with the new grid. With only a few cursor movements and writing a few characters, it is able to render the output. The grid is represented as a dictionary of dictionaries. Where the keys are line and row numbers and the values are ``Char`` instances. (these are string/token combinations).

If we would allow inserting token lists like ``(Token.Raw, "\033]133;A\a")``, then we should assume that the user who constructed the escape sequence is knowledgeable enough to be sure that it doesn't produce any cursor movements and it's actually a zero-width sequence. In this case, we can append it to the previous character in the grid. Just like the second part of a decomposed unicode character.

For the very first part ("begin of prompt"), there is nothing right before it to append, but with a few tricks it could be possible to render it in the output. I have to think about that.

It doesn't seem like there is a lot of documentation around this feature... Only iterm2 supports it, and only the beta release.

Is there some official documentation on how it works in situations with cursor movements? What if such a sequence is printed, followed by backspace/delete? What if the escape sequence is sent at a certain cursor position, and then we move the cursor back and overwrite that position? What if the prompt gets replaced by a ``(reverse-i-search)``-prompt? Are we allowed to send the "end-of-prompt" at the new end-position? What happens if we clear the screen and redraw the prompt at the top of the screen?
Are we allowed to send the output without these escape sequences, then do cursor movements to the start/end position and write these escape sequences, followed by moving the cursor back into place? I would like to see a specification/rfc/document for this.

Usually, I keep xterm as a reference. xterm has a long history and feels like the best implementation of a terminal emulator. (You don't realize how buggy most of the terminals are until you start experimenting with tools like ``vttest``.) And xterm doesn't support this yet.

Also, if the only possible implementation is to do a certain check for each character in the output grid, before writing it. That would be too expensive. The code is highly optimized to feel as responsive as possible.

Because of that, my proposal to draw the prompt once, right before prompt-toolkit comes into action, by sending out the following sequence:
``'\033]133;A\aIn[1]:\033]133;B\a\r'`` - and possible send a clear-until-end-of-line afterwards. If the terminal is clever enough to remember this, then that should be enough.

I will think about it, but as you can see, there are still many questions.

**Comment by asmeurer** [comment]
> If we would allow inserting token lists like (Token.Raw, "\033]133;A\a"), then we should assume that the user who constructed the escape sequence is knowledgeable enough to be sure that it doesn't produce any cursor movements and it's actually a zero-width sequence. In this case, we can append it to the previous character in the grid. Just like the second part of a decomposed unicode character.

That's no different than readline requiring you to wrap invisible characters with `\001` and `\002`.

**Comment by asmeurer** [comment]
CCing @gnachman on the iTerm2 questions.

**Comment by jonathanslenders** [comment]
Ok, the analogy with ``\001`` and ``\002`` makes sense. Any place where I can find more information about those two readline escapes?

**Comment by asmeurer** [comment]
I don't remember finding a particularly great reference back when I was trying to figure out what they were. I think I ended up reading the source code to figure it out, but basically, anything invisible bytes (like control characters, which won't render when displayed) should be wrapped in the bytes `\001` and `\002`, so that readline can count the number of visible characters correctly. If you fail to do this you get weird behavior where the text you type overwrites your prompt. By the way, `\001` and `\002` are also known as `\[` and `\]`.

**Comment by gnachman** [comment]
> It doesn't seem like there is a lot of documentation around this feature... Only iterm2 supports it, and only the beta release.

FinalTerm supported it too, but alas it is no more. I hope after 3.0 exits beta that other terminals will add support for this feature, but that remains to be seen.

> Is there some official documentation on how it works in situations with cursor movements? What if such a sequence is printed, followed by backspace/delete?
> What if the escape sequence is sent at a certain cursor position, and then we move the cursor back and overwrite that position? What if the prompt gets replaced by a (reverse-i-search)-prompt? Are we allowed to send the "end-of-prompt" at the new end-position? What happens if we clear the screen and redraw the prompt at the top of the screen?

The bash script sends an "end-of-output" code with no preceding "start-of-output" code after you enter your query at the `(reverse-i-search)` prompt. This is called an "abort", and removes the mark and erases all recorded state about the preceding prompt. This is not documented, and that was an oversight on my part.

> Are we allowed to send the output without these escape sequences, then do cursor movements to the start/end position and write these escape sequences, followed by moving the cursor back into place? I would like to see a specification/rfc/document for this.

Yes; because commands are interactively edited, this must be supported (at least for the text between the end-of-prompt code and the start-of-output code; I think that's what we're talking about). I'm not aware of a forum where one can publish an RFC for this kind of thing, but I'm open to suggestions. The spec I wrote is as good as it gets today.

> Usually, I keep xterm as a reference. xterm has a long history and feels like the best implementation of a terminal emulator. (You don't realize how buggy most of the terminals are until you start experimenting with tools like vttest.) And xterm doesn't support this yet.

xterm is really good at emulating a DEC, but doesn't tend to lead the way on features.

Other than improving the documentation around the FinalTerm escape sequences to document command cancellation and when you can move the cursor back past a finalterm escape code and that editing the command is OK, what can I do to help you?

**Comment by Carreau** [comment]
I found this reference:

http://superuser.com/questions/301353/escape-non-printing-characters-in-a-function-for-a-bash-prompt

That i'll reproduce here for convenience:
--- 
The readline library accepts `\001` and `\002` (ASCII SOH and STX) as non-printable text delimiters. These also work in any application that uses readline.

From `lib/readline/display.c:243` in bash source code:
```
243 /* Current implementation:
244         \001 (^A) start non-visible characters
245         \002 (^B) end non-visible characters
246    all characters except \001 and \002 (following a \001) are copied to
247    the returned string; all characters except those between \001 and
248    \002 are assumed to be `visible'. */
```
The bash-specific `\[` and `\]` are in fact translated to `\001` and `\002` at `y.tab.c:7640.`

Note: If you use bash's `printf` or `echo -e`, and if your text has `\001` or `\002` immediately before a number, you'll hit a bash bug that causes it to eat one digit too many when processing octal escapes – that is, `\00142` will be interpreted as octal `014` (followed by ASCII "2"), instead of the correct octal 01 (followed by ASCII "42"). For this reason, use hexadecimal versions `\x01` and `\x02` instead.

---

**Comment by gnachman** [comment]
Official docs for FinalTerm's escape sequences as used in iTerm2's shell integration.

https://iterm2.com/finalterm.html

Comments are welcome here or in an issue (iterm2.com/bugs)

**Comment by jonathanslenders** [comment]
Please have a look at this pull request. https://github.com/jonathanslenders/python-prompt-toolkit/pull/299 (check out the branch and test in iterm2.) 

https://github.com/jonathanslenders/python-prompt-toolkit/blob/zero-width-escapes/examples/finalterm-shell-integration.py

For me, it seems to work, but not 100% sure whether I'm not missing something.
Also, I need to do some performance testing.

**Comment by ahundt** [comment]
Anyone know the steps to actually turn this on with each of finalterm and iterm2?

**Comment by asmeurer** [comment]
It depends on what shell you are using. Using iterm2-tools, add 

```
(Token.ZeroWidthEscape, iterm2_tools.BEFORE_PROMPT),
```

```
(Token.ZeroWidthEscape, iterm2_tools.AFTER_PROMPT),
```

To the beginning and end of your prompt tokens.  And you also need to use BEFORE_OUTPUT and AFTER_OUTPUT, which generally requires some support in the shell for running some pre- and post-command hooks (see https://iterm2-tools.readthedocs.io/en/latest/shell_integration.html).

If you don't want to depend on iterm2-tools you can copy the code from [here](https://github.com/asmeurer/iterm2-tools/blob/master/iterm2_tools/shell_integration.py).

**Comment by jonathanslenders** [comment]
Closing this, support for these escape sequences have been implemented more than a year ago.
See this example for how to use it in prompt_toolkit 2.0: https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/examples/prompts/finalterm-shell-integration.py
