### ISSUE TITLE
Reserving the bottom lines for completion in xonsh

### ISSUE THREAD

**Issue by melund** [jonathanslenders/python-prompt-toolkit#163]
Hi 

I think my reply got lost in a closed issue... So I am just creating a new issue instead.

@jonathanslenders . I tried to test this, your solution for reserving the lower lines for completion. It no longer scrolls up just as I hit tab, but the problem is still the same. Now scrolling just happens just when a command is executed. It can best be explained with a video.

[![ScreenShot](https://cloud.githubusercontent.com/assets/1038978/9493195/4a4e4b40-4bfe-11e5-9332-10b131d448fd.png)](https://youtu.be/61tEgbNKTmM)

Btw. When I press tab at the start of a line. It inserts the tab characters as well as opening the completion box. (see the end of the video). Any idea if this is due to xonsh or prompt_toolkit?

**Comment by jonathanslenders** [comment]
Hi @melund,

This is certainly a bug. I think the scrolling only happens on Windows consoles, but it should be fix. I'll try to do it before the next release.

The second thing, that "tab" does both, is also a bug. I'll fix that.

Jonathan

**Comment by jonathanslenders** [comment]
I think this commit should fix it: https://github.com/jonathanslenders/python-prompt-toolkit/commit/be4169f423270992ccd6477241bcd2c057956559

**Comment by jonathanslenders** [comment]
The second issue (tab inserts whitespace) is an issue in Xonsh.

In ``xonsh/prompt_toolkit_key_bindings.py`` is a key binding defined for ``Tab`` which inserts the tab characters. This will happen always if there is only whitespace before the cursor at the current line.
This could be intended. (I don't know.)

However, 'tab' does not cause the completions to be shown. They are generated on any character insert. ``get_input`` has an optional parameter ``complete_while_typing`` which is ``True`` by default. When ``False``, pressing tab would always be required. I think however it's okay like it is right now. 

On the other hand, what could be an issue, is that completions are shown when a whitespace character is pressed. Maybe you want ``complete_while_typing`` to only generate completions when a non-whitespace character is inserted, and otherwise, show require the user to press the tab key explicitely. You can do this by looking at the ``CompleteEvent`` instance that you receive in ``Completer.get_completions``. (That is a function that Xonsh implement.) If ``CompleteEvent.completion_requested`` is True, the user asked for a completion by pressing the tab key. If it's False, the user did inserted some text. In the latter case you can see which character he inserted by looking at the character before the cursor in the document parameter. When it's a whitespace character, don't return any completions.

Please let me know when something is unclear.

**Comment by scopatz** [comment]
Is there something that we need to do in xonsh for the tab-issue?

**Comment by jonathanslenders** [comment]
Yes, given the custom key binding, I expect that the tab insert is correct, but the autocompletion menu should not be shown.

So, ``Completer.get_completions`` should not return anything when ``complete_event.text_inserted`` is True (That's when ``complete_event.completion_requested`` is False.) and the character before the cursor is whitespace. (Or a tab.) I can create a pull request for this if that helps.

**Comment by scopatz** [comment]
A PR would be super helpful because I am pretty unfamiliar with the prompt-toolkit part of the code base.

**Comment by scopatz** [comment]
:)

**Comment by jonathanslenders** [comment]
I just discovered that there is actually a bug in the ``completion_requested`` value. I will fix that and then make a pull request.

**Comment by scopatz** [comment]
Thanks @jonathanslenders!

**Comment by scopatz** [comment]
I believe that this has been addressed. Feel like we can close @melund?

**Comment by melund** [comment]
I do..
