### ISSUE TITLE
[question] Backwards-incompatible changes

### ISSUE THREAD

**Issue by jakubjedelsky** [jonathanslenders/python-prompt-toolkit#194]
Hi,

I would like to create a rpm package for Fedora/EPEL as a dependency for some other packages, but it will be quite difficult because of a lot of backwards-incompatible changes. It's well documented (thanks for it), but don't you want to deliver more bugfixes/improvements without these incompatibilities? It's very hard and uncomfortable to use newer version when some eg. class is just renamed. It will be nice to have incompatibilities between a major versions (I can deliver new major version to a new version of distribution), not minor.

Thanks.

**Comment by jonathanslenders** [comment]
Hi @jakubjedelsky,

This is possible, yes. But there is a reason I choose not to do it right now.

The prompt_toolkit library is still very young (I think it started about two years ago). In many ways, the design has been changed over time, in order to make it as good as possible. Currently, I consider some of APIs unstable, because new use cases are starting to emerge and we want to be as flexible as possible. Unfortunately, right now, there is no way I will be able to support multiple branches. (Like backporting features or bug fixes to older versions, and doing multiple releases every time.) So, for now, it's best to consider every single release (each one that is still starting with a zero), to be a major upgrade, that is incompatible and cannot be done automatically.
By the way, in the Python world, we prefer to use pip to install packages, rather than rpm or deb packages, and pip is able to correctly install the right dependencies. (So, there's it's not much of an issue.)

However, I seriously intend to move to a version scheme with major/minor version numbers, where minors don't introduce backward-incompatible changes. But currently, I'm first experimenting with a few more projects that depend on prompt_toolkit and which will heavily challenge the design. I expect that a few more backwards-incompatible changes are possible, but hopefully in a few months, we can move to a version 1.0 and consider the API stable.

Jonathan

**Comment by jakubjedelsky** [comment]
Hi Jonathan,

thanks for reply. I understand you, but your library is already used by a few projects and these can't be used together right now. I checked projects mentioned in [readme](https://github.com/jonathanslenders/python-prompt-toolkit#projects-using-prompt-toolkit) and found, that I need 5 different versions of prompt_toolkit to use it (doesn't matter if pip or rpm/deb).

Well, I'll try to prepare newest version and if something will depend on it, one have to create patch. Simple enough :) Hope it will work for some time.

And hope you'll find your cool library mature soon, many thanks for your work!

J.

**Comment by kitterma** [comment]
Speaking as one of the prompt-toolkit maintainers for Debian (where we packaged it because applications that were already packaged started using it), I share this concern.  I started looking at updating to the newest release in Debian and got depressed at the number of incompatibilities I needed to evaluate for impact on other packages.

In previous versions you've maintained the old names while adding the new ones to promote backward compatibility.  It would be great if you could continue to do that until things stabilize.  The prompt-toolkit users aren't keeping up.

**Comment by jonathanslenders** [comment]
Hi @kitterma,
Thanks for sharing this concern! I will take this seriously.
Jonathan
