### ISSUE TITLE
customize amount of reserved space

### ISSUE THREAD

**Issue by scopatz** [jonathanslenders/python-prompt-toolkit#195]
Hi! It seems like using prompt-toolkit with xonsh reserves 8 lines at the bottom minimum. See https://github.com/jonathanslenders/python-prompt-toolkit/blob/9e96e1bf815b07edb5c266bf2ba9ae1d6e350746/prompt_toolkit/shortcuts.py#L232-L238 This is far too large to be usable for me.  Is there any way that this could be customizable in some way? I'd *really* appreciate it...

See the xonsh list for more discussion: https://groups.google.com/d/topic/xonsh/Y3L9GAcFwGM/discussion

**Comment by scopatz** [comment]
ping, any ideas?

**Comment by jonathanslenders** [comment]
Hi @scopatz,

Yes, that should be possible. I will make it configurable.
(Sorry for the delay, I'm just coming back after being abroad for a week.)

**Comment by scopatz** [comment]
Thanks @jonathanslenders! Sorry about being impatient :). I am starting to use ptk in xonsh myself regularly and so my proclivities are coming to the fore.

**Comment by jonathanslenders** [comment]
Just a short message to say that I have not forgotten about this. By the end of this month I will have two weeks off and that should give me some time to do more development again.

**Comment by scopatz** [comment]
Thanks @jonathanslenders!

**Comment by redshodan** [comment]
+1 on making it configurable. This might be out of scope of this ehancement request, but would it be possible to have the completion menu be displayed above the prompt line in a sort of "pop-up" menu style? I'd rather not lose any space at all to it. I'm sure that would be a bit more work than just making the reserved space configurable. :)

**Comment by jonathanslenders** [comment]
I'd very much like to show it always above the prompt. However that's very difficult, because we have to redraw the text underneath at the point where we hide the menu. Usually we cannot be sure what was displayed there, because the output could come from anywhere. It is also not possible to ask the terminal to report the visible text.

However, one (very complex) solution (which only works on posix) would be to use a vt100 emulator, and create a kind of proxy between stdout and the real pty. I'm investigating that path, but currently it doesn't look very feasible or it would break the scrollback buffer.

Making it configurable is easy. (I'll do that.)

**Comment by redshodan** [comment]
I had kind of assumed PT was already doing something like that. One option might be looking at the MOSH code. They fully emulate a unicode vt1XY (forget which exact one) terminal so they can do various tricks. Their docs have comments about running into various TTY bugs that they had to fix. That's all C code, and I don't know if its acceptible to pull in, or worth doing the effort to replicate it in Python. And you're right that it would only help on posix. I'm sure that would be a huge effort. Oh well. :)

**Comment by scopatz** [comment]
I have started to try to work around this in xonsh, see the [`ptk-prompt` branch](https://github.com/scopatz/xonsh/tree/ptk-prompt). However, even though I figure out how to change the amount of reserved space, the tab completion menu won't pop-up if the amount of reserved space is too low (say min=0 or 1).  Is there any way to do this? Or alternatively, is there any way for the menu to appear above the prompt line?

**Comment by jonathanslenders** [comment]
The space for the menu is now configurable: https://github.com/jonathanslenders/python-prompt-toolkit/commit/f3aeb272956110aacf0a1db1426118b3cb9f2ffd
(Still needs to be released, but I'll probably push a new release in January, after some testing.)

Prompt_toolkit does not simulate a  vt100 terminal, but a future version could probably do that on Posix platforms. I'm investigating that.

**Comment by scopatz** [comment]
Thanks @jonathanslenders!

> Prompt_toolkit does not simulate a vt100 terminal, but a future version could probably do that on Posix platforms. I'm investigating that.

Forgive my ignorance, but I am not sure how that will help. Is this related to the positioning issues?

**Comment by jonathanslenders** [comment]
Yes. If we are able to fully simulate a vt100 terminal, then we can build a more complex layout that covers the full screen (but without going to the alternate screen buffer). Something like this.
```
+-----------------------+
|  vt100 emulator       |
|                       |
|                       |
|                       |
|                       |
|                       |
+-----------------------+
| >>> input area        |
|                       |
|                       |
+-----------------------+
```
The input area is the command line, like it looks right now. But everything above is a "transparent" vt100 emulator. In linux/unix, we can create a custom pty (by calling openpty). Then we could attach the slave side to stdin/stdout. (by calling os.dup) and add the master side as an additional reader to the eventloop. So, everything that is written to the output (by a subprocess, or from Python itself, will go through this pty, and prompt_toolkit will render it through the vt100 emulator, as part of the layout.

This means that prompt_toolkit becomes aware of everything above the main layout, and we'll be able to draw completion menus over the whole screen.

However, there are some drawbacks:
- The prompt_toolkit application (the eventloop) has to run all the time. This is required for redirecting the output. This also means that commands have to be handled in an executor. (Another thread.)
- It will not run on Windows.
- The setup could be complex to understand. So, I would want a way to easily switch between this layout and the one without a vt100 proxy.

I should admit, that this approach is tempting, especially because I start to believe that this is possible. However, the actual implementation will probably take a few months or even a year when I will start attempting it.

**Comment by scopatz** [comment]
Ahh thanks for the detailed explanation @jonathanslenders. As far as xonsh is concerned, no need to go through such herculean efforts. We generally want things to work the same on all platforms so a lack of windows availability for this would not help us so much :).

Frankly, this kind of thing seems to be what ncurses / urwid is for.

**Comment by scopatz** [comment]
Also, I am happy to close this, if you are.

**Comment by scopatz** [comment]
For what it is worth, I figured out how to get prompt-toolkit to resize the reserved space on a tab-event. I'll open a new issue for this, though.

**Comment by jonathanslenders** [comment]
Ok, I'm closing this one. Don't hesitate to open a new issue for other things.

**Comment by scopatz** [comment]
Thanks again @jonathanslenders!
