### ISSUE TITLE
Use style_from_pygments

### ISSUE THREAD

**Issue by 38elements** [jonathanslenders/python-prompt-toolkit#232]
`PygmentsStyle` is [deprecated](https://github.com/jonathanslenders/python-prompt-toolkit/blob/d4a73d0e13fdc97480ee780e4d90743825bbebc8/prompt_toolkit/styles/from_pygments.py#L55).

`PygmentsStyle` exists in the following file.

[examples/bottom-toolbar.py](https://github.com/jonathanslenders/python-prompt-toolkit/blob/c7e7160ceb7a682771f2132478a30e6256d707b6/examples/bottom-toolbar.py#L11) 
[examples/print-tokens.py ](https://github.com/jonathanslenders/python-prompt-toolkit/blob/1b6ae2cf2c67df7f72df74947475f6879ecdde1a/examples/print-tokens.py#L12)
[examples/regular-language.py ](https://github.com/jonathanslenders/python-prompt-toolkit/blob/e41cee9e541fe83f9cf9f07385862de372c66225/examples/regular-language.py#L40)
[prompt_toolkit/shortcuts.py ](https://github.com/jonathanslenders/python-prompt-toolkit/blob/127f421890d4da09170aeaa720698ad879b1939f/prompt_toolkit/shortcuts.py#L424)

**Comment by jonathanslenders** [comment]
Thank you!

**Comment by jonathanslenders** [comment]
Fixed in: https://github.com/jonathanslenders/python-prompt-toolkit/commit/60fed1105392cd4ac4588406b19e8b1f52c1ea21  (I'm not sure whether or not we still need style_from_pygments, just ``style_from_dict`` looks enough for about every situation. ``style_from_pygments`` is only for the case where you'd like to merge a Pygments dictionary and custom styling.)

**Comment by 38elements** [comment]
Thank you.
