### ISSUE TITLE
ControlH & backspace clash ?

### ISSUE THREAD

**Issue by Carreau** [jonathanslenders/python-prompt-toolkit#257]
Ok, so this is likely me who does something weird. 

I've the following in a playground:

```python
@registry.add_binding(Keys.ControlH, eager=True)
def makeh(event):
    event.cli.application.layout = hlayout
```

Where hlayout is an HSplit, (and same for CtrlV that make a VSplit)

it **seem** that **sometime** when I press backspace when typing a text in one of the buffers, the `makeh` callback is triggered. Of course, murphy's law, I can't reproduce it when I want, or it's likely that this is not backspace itself, but a thing I do at the same time without realizing, so just opening an issue in case you just know why.

**Comment by jonathanslenders** [comment]
Hi Matthias,
For a vt100 terminal (probably, any unix terminal) Control-H and backspace are actually the same key. There is no way for the application to know what the user actually pressed. It's like Tab and Control-I are also the same key.

About ``eager``, normally you don't need that. (It should not become a habbit to use that for every key binding.) It only makes sense if you want to replace all other key bindings that start with ControlH, rather than only ControlH itself. So, if there was ``C-H C-X``; without having ``eager=True``, the handler for ``C-H`` would only be executed after we know what key was pressed as a second key. E.g. if the user presses ``C-H C-Y``.

**Comment by Carreau** [comment]
OK, thanks ! I didn't new that. The weird thing then is that sometime it does not seem to conflict, it just do not erase the char in the buffer. I might just be confused, Thanks !

Closing.

**Comment by ppwwyyxx** [comment]
These days there are many terminals that are able to distinguish ctrl-h and backspace. IMO the choice to clash the two keys should be revisited.

https://github.com/prompt-toolkit/python-prompt-toolkit/blob/4432d6233fd8e0efba5920a9650e515f54a20300/src/prompt_toolkit/input/ansi_escape_sequences.py#L58-L64

I'm able to workaround this by a hack to map backspace to a different, unused key:
```
    from prompt_toolkit.input.ansi_escape_sequences import ANSI_SEQUENCES
    ANSI_SEQUENCES['\x7f'] = Keys.ControlF24
```
