### ISSUE TITLE
DeprecationWarning in Py3

### ISSUE THREAD

**Issue by inducer** [jonathanslenders/python-prompt-toolkit#263]
```
/home/andreas/pool3/lib/python3.5/site-packages/prompt_toolkit/filters/base.py:76: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  return inspect.getargspec(self.__call__)
/home/andreas/pool3/lib/python3.5/site-packages/prompt_toolkit/filters/base.py:242: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  return inspect.getargspec(self.func)
```

**Comment by jonathanslenders** [comment]
Thanks for reminding me @inducer. I knew about this, but usually, this error is not shown, and somehow I forgot to actually do something about it.
I'll mark this issue a bug (while actually it isn't), to be sure I'll replace this by ``inspect.signature()`` on Py3 for the next release, because it should be done.

**Comment by jonathanslenders** [comment]
This was fixed in: https://github.com/jonathanslenders/python-prompt-toolkit/commit/6c78c010bf7f554a4da8dea98cdd573df8e6fa04
