### ISSUE TITLE
Completer and lexer based on a context-free grammar?

### ISSUE THREAD

**Issue by eliangcs** [jonathanslenders/python-prompt-toolkit#276]
It is a good idea to generate a completer and a lexer based on a single grammar. I see you have a grammar-based completer and lexer for regular languages in `prompt_toolkit/contrib/regular_languages/`. But what if I expect my user input is a context-free language? I'm not an expert in this area, so I don't even know if this is doable. Can you provide some guidance if I'm going to implement this?

**Comment by jonathanslenders** [comment]
That's a good question.
The short answer is that it's probably not a good idea.

It would be complex to generate a completer from the grammar of a context-free grammar. A completer has to deal with incomplete inputs. Parsing that while being tolerant for syntax errors and still making enough sense of it in order to provide a meaningful completion is hard. On the other hand, just looking what is right before the cursor and trying to make sense of that is easy, but one has to write the logic manually.

It is true that ``contrib.regular_languages`` contains an effort to automatically generate a lexer/completer from a regular grammar. This seems to work for simple examples. We take a grammar, and turn it into another grammar that matches incomplete inputs. However, as the first grammar grows, the second one grows exponentially, and it becomes heavy to deal with. I'm still using it in ptpython for something simple, but I consider moving away from it.

There are probably better approaches. For Python, we have Jedi now that does most of the auto completion work. It's incredibly good, but Jedi is not easy to understand, and not something you will simply apply to another language.

For the lexing, it is easier. Actually, I believe that a lexer will always use a regular language. Even if you have a lexer for a context-free language, the lexer still uses regex. (This is why there are two steps while interpreting a language: lexing & parsing.) Further, a lexer can cope remarkably well with an incomplete input. So, because of that, we can use the Pygments lexers for everything.

Does that makes sense?

**Comment by eliangcs** [comment]
Thank you for your detailed explanation.

So are you suggesting, instead of unify lexer and completer with a grammar, it would be more efficient if I just write the lexer and completer specific for the language of my user input?

**Comment by jonathanslenders** [comment]
Exactly, most of the time, that's going to be the most practical.

**Comment by eliangcs** [comment]
Then I'll do that. Thanks a lot!
