### ISSUE TITLE
can't come out of full-screen-layout.py example on osx

### ISSUE THREAD

**Issue by amitu** [jonathanslenders/python-prompt-toolkit#278]
Ctrl-C nor Ctrl-Q or Ctrl-Shift-Q had any effect. 

Also after killing the process from another window, Ctrl-C/Ctrl-D was not getting passed to shell from where I launched the process.

**Comment by jonathanslenders** [comment]
Hi @amitu ,

ControlQ and ControlS are reserved key bindings in many terminals.
Try to execute ``stty -ixon`` before running the example. This should disable flow control.

Probably I should have used another key binding to demonstrate.

It is possible that some key sequences don't work anymore after killing the process. Prompt-toolkit turns the terminal into raw mode, and because it's killed it can't restore it. Try to execute ``reset`` followed by enter in the terminal. That should restore it.

Jonathan

**Comment by amitu** [comment]
@jonathanslenders thanks.
