### ISSUE TITLE
CommandLineInterface doesn't accept its default eventloop parameter

### ISSUE THREAD

**Issue by takluyver** [jonathanslenders/python-prompt-toolkit#287]
Hi Jonathan. In the [CommandLineInterface constructor](https://github.com/jonathanslenders/python-prompt-toolkit/blob/740d468a468dd6f17cb8ada6f6abfaf5637900d9/prompt_toolkit/interface.py#L65), the `eventloop` parameter has a default of None, but it then immediately checks `isinstance(eventloop, EventLoop)`, so you can't instantiate it without passing eventloop in. This is biting us for jupyter_console. Should it accept None, or is that parameter now required?

**Comment by jonathanslenders** [comment]
This was removed on purpose because an `EventLoop` instance needs to be closed explicitely. (It allocates a unix pipe which could leak otherwise.)
So, you probably want to wrap it in a try/finally, like in this example: https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/examples/full-screen-layout.py#L176

I will remove the ``=None``, because the default doesn't make any sense.

**Comment by takluyver** [comment]
Thanks, I've added code to explicitly close it.
