### ISSUE TITLE
Is it possible to update grammar or lexer of an already running prompt

### ISSUE THREAD

**Issue by lovesh** [jonathanslenders/python-prompt-toolkit#346]
This is a question.
I have created an application like this
```
lexers = {n: SimpleLexer(Token.Keyword) for n in ["cmd1", "cmd2", "cmd3"]}
grammar = compile("".join(["regex1", "regex2", "regex3"]))
grammarLexer = GrammarLexer(grammar, lexers=lexers)
completers = {
            'node_command': WordCompleter(['word3', 'word4', 'word5', 'word6']),
            'client_command': WordCompleter(['word7', 'word8', 'word9']),
            'client': WordCompleter(['word1', 'word2'])
}
grammarCompleter = GrammarCompleter(grammar, completers)
app = create_prompt_application('{}> '.format(name),
                                        lexer=grammarLexer,
                                        completer=grammarCompleter,
                                        style=style)
cli = CommandLineInterface(
            application=app,
            eventloop=eventloop)
```

This works fine but now depending on a user's command (say a new plugin is loaded using a prompt command), i want to update the `lexer` as well as `completer` of the `app`. I tried updating the completer of the application by reseting the grammar of the buffer as
`app.buffer.grammar = newGrammarCompleter` 
but this does not work. Any other option i have except loading all the possible lexers and grammar that the prompt can have?

**Comment by jonathanslenders** [comment]
Hi @lovesh,

Are you sure that you didn't assign to ``buffer.completer`` instead of ``buffer.grammar``. It should be ``completer``. However, in general, prompt-toolkit tries to work more in a functional way. That means that we consider objects immutable, and try to avoid assignments. So, instead of this:
```
app.buffer.completer = newGrammarCompleter 
```
we can also create a ``completer`` object that acts as a proxy to another completer and is more dynamic.
Have a look at how the completer interface works: https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/prompt_toolkit/completion.py#L98

So, we can then create a dynamic completer:

```python
class DynamicCompleter(Completer):
    def get_completions(self, document, complete_event):
        # Right here, take a look at what currently would be the active completer class:
        completer = get_current_completer()  # To be implemented

        return completer.get_completions(document, complete_event)
```

In general, we try to encourage the second approach, but use whatever you prefer.

Jonathan

**Comment by lovesh** [comment]
@jonathanslenders Hey, you are right, it had to be `app.buffer.completer = newGrammarCompleter `. Thanks. But the prompt still shows like it does not recognize the command, looks like i needs to update the lexer too

**Comment by lovesh** [comment]
I had to replace the `lexer` as `app.layout.children[1].children[1].content.content.lexer = newGrammarLexer`.
