### ISSUE TITLE
Fullscreen Application Examples

### ISSUE THREAD

**Issue by zhfuzzy** [jonathanslenders/python-prompt-toolkit#350]
Hi jonathan,

Thanks for the wonderful library! Currently I'm trying to build some console-based UI which should goes like this

```
┌──────────────────────────────────────────────────────┐
│                                                      │
│           ( displaying some text and                 │
│               maybe some ascii graph  )              │
│                                                      │
├────────────────────────────┬─────────────────────────┤
│                            │                         │
│  (a real terminal like     │    ( a custom shell     │
│      you did in pymux)     │        like ptpython )  │
│                            │                         │
└────────────────────────────┴─────────────────────────┘
```

But right now I have got no idea on how to:
- embed a real termial to a fullscreen application
- embed a custom prompt to a fullscreen application
in to this full screen prompt_tool kit app.

I've play around with the `example/full-screen-layout.py` and other examples, yet finding no clue on archiving my goals. Can you add some examples on fullscreen application with `prompt()`?

BTW, I've read the pymux for couple of hours but getting lost in Pane, Window, Clients... Is there any early code in pymux's development, which is only about launching a shell under the control of prompt_toolkit?

**Comment by jonathanslenders** [comment]
Hi @zhfuzzy,

Thanks for the interesting question!

This is possible, however not trivial. In order to embed a terminal, there's a lot to do, and I don't want to suggest that the way to do it, is to reproduce code from pymux, because that will be difficult to maintain, especially without a deep understanding of how pseudoterminals and many posix concepts work. (I made it too complex, unfortunately.)

The problem is mostly that prompt-toolkit was in the first place designed for creating simple input lines, like GNU Readline. Later, prompt-toolkit became much more powerful; however some parts of the internal API reflects that it it was not meant to create full screen applications. One example is that key bindings are defined globally, and not per UI widget. Further, the focus is defined by a "Buffer" data structure that has the focus, again instead of a UI widget. This is very inflexible for full screen applications as they become bigger. It also makes it impossible to create a reusable "terminal" widget that can be embedded in other applications.

I'm very aware of this and started working on a branch that refactors the API for full screen applications to make this as easy as it is for creating simple prompts. There's still a lot of work to be done. For me, this is a priority, but it can easily take 6 more months.

So, unfortunately, the answer is that right now, it is possible, but very difficult. And I don't have the time to support custom full screen applications built on the current API. But I very much believe that in about a year, this should be super easy. I hope you understand.

[1] https://github.com/jonathanslenders/python-prompt-toolkit/tree/full-screen-widgets

**Comment by zhfuzzy** [comment]
I understand that `prompt_toolkit`, by it's name, is not meant to be used as a fullscreen terminal framework, so thanks for the effort you made in extending it. 

I'm trying to understand `pseudo-terminals` and some `prompt_toolkit`'s internal by cutting pymux codebase into small pieces and stepping through the code base, but still, if there are any articles and experiment code you used in the early stage of `pymux`'s development, you may put them in the documentation of `pymux` for new comers to get started.
