### ISSUE TITLE
Possible to add Control+0, Control+1, etc. as keys?

### ISSUE THREAD

**Issue by reckoner** [jonathanslenders/python-prompt-toolkit#352]
Is it possible to add the `Control+0` or other `Control` plus number keys as bindings?

**Comment by zhfuzzy** [comment]
As long as I've tried in xterm and some xterm-compatible terminals, the `Control+NUM` sequense are not all get passed to the program running in the terminal.
I used this [sample code](https://gist.github.com/zhfuzzy/39827f7f77139bf4d776ff28f1e672f8) for testing, you may have a try.
The reason, though, is unclear for me, since I didn't find any clue in the [escape sequence](http://www.ccs.neu.edu/research/gpc/MSim/vona/terminal/VT100_Escape_Codes.html), explainations are appreciate.

**Comment by jonathanslenders** [comment]
As far as I know, this is not possible on a Vt100 terminal.
Some control-keys will actually generate some input, but they seem to be aliases only for other control keys.

On, my keyboard for instance some control-number combinations result in: backspace, control-backslash, control-], control-^ and control-_.  Some control-number combinations don't do anything at all.

**Comment by jonathanslenders** [comment]
Closing this. I think there is nothing we can do here...
