### ISSUE TITLE
[feature request?  bug?] iPython up-arrow partial string matching doesn't work

### ISSUE THREAD

**Issue by shanusmagnus** [jonathanslenders/python-prompt-toolkit#36]
iPython does partial string matching from its history when using the up arrow.  For instance, if you have previously executed:

    import abacus
    import monkeypants
    import mvpa_stuff_ex
    import zebra

and later you type:

    import mv

and then hit up arrow, iPython will match history based on the existing input line and only present you with a possibly-matching option.  This no longer happens when using ptipython.  Presumably it's because the ptpython family is doing its own stuff with the arrows to support cool features like multi-line editing and selecting from options in completion-matching; but this history-substring-matching in iPython is a must-have for me.  Could ptipython be compelled to allow iPython's behavior to pass through?

**Comment by jonathanslenders** [comment]
Hi all,

I'm about to implement this "history-substring-matching".
Is that an option that can be enabled/disabled in readline? What is it called exactly?

I think I know how to implement it, and probably it's not even that hard. But I'd like to be as compatible as possible with readline.

Cheers,
Jonathan

**Comment by manova** [comment]
@jonathanslenders if you implemented it in a fork, I would definitely use it. I'm also willing to help out. What was your plan exactly for implementing it?

**Comment by jonathanslenders** [comment]
Hi @manova (and everyone),

It is implemented. Have a look at this example: https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/examples/up-arrow-partial-string-matching.py
Like for readline, the option is called "history searching".

It's also configurable for ``ptpython`` and ``ptipython``. (From the options menu, or from a configuration file.)

There is only one trade-off. It's not possible to have both this feature and ``autocomplete_while_typing`` enabled, otherwise the key bindings are ambiguous. So, with history searching on, you have to press ``tab`` to trigger autocompletion.

Feedback is welcome. :)

Cheers,
Jonathan
