### ISSUE TITLE
Hyphen or underscore in library name?

### ISSUE THREAD

**Issue by therden** [jonathanslenders/python-prompt-toolkit#362]
There seems to be some confusion about the name of this library:  specifically, whether a hyphen or an underscore separates 'prompt' and 'toolkit'.

- The README.rst file in the repo sometimes uses one and sometimes the other form.  For example, the pip install instructions found there use the hyphenated form of the name.
 
- In contrast, except for the URL itself (which uses a hyphen), the readthedocs site seems to consistently use an underscore in referencing the library -- even within the pip install instruction which appears there.

- Within PyPi, the library can only be found using the underscore version of the name.  But "pip install prompt-toolkit" _does_ work!

**Comment by jonathanslenders** [comment]
Hi @therden,

Thank you for pointing this out. I think I'll sattle on using the underscore everywhere, because this this the only notation that works in Python source code. In URLs however, people usually prefer dashes instead of underscores, so in those cases, I'd keep it like that. I fixed the readme.

**Comment by therden** [comment]
You're welcome.  I would have made the changes and submitted a pull request, but I wasn't certain which variation to go with.  `prompt_toolkit` is a great library -- thank you for sharing it.

**Comment by jonathanslenders** [comment]
You're welcome!
