### ISSUE TITLE
Smart auto-compete

### ISSUE THREAD

**Issue by anhtran** [jonathanslenders/python-prompt-toolkit#39]
Love to have something like this:

```
from urllib.parse import join  ==> urljoin
```

I used to see this feature in IntelliJ.

**Comment by CharString** [comment]
@jonathanslenders I think he meant something else. `urllib.parse` doesn't contain a name `join`, but it does have a name `urljoin`. I think he meant the completer should use `in` instead of `startswith`.

I suppose this is handled by jedi. And I suspect this gives weird behavior on the second <kbd>tab</kbd> press, as the word before the cursor is something different than the user entered himself. To have it behave intuitively, it would require more state. But I may be wrong.

**Comment by jonathanslenders** [comment]
Closing this issue, because it's meant for ptpython, not prompt_toolkit. (Which has a different repository now.) We use indeed Jedi, so this would have been something to request for the Jedi library.
