### ISSUE TITLE
Implement "operate-and-get-next (C-o)"

### ISSUE THREAD

**Issue by mgalgs** [jonathanslenders/python-prompt-toolkit#416]
One useful feature in `bash` is to go back in history, find a command you want to execute, and execute it, loading the next command.  This is useful for repeating sequences of related commands that are often repeated together.  It's bound to `C-o` in `bash` and `zsh` (and probably others).

You can see how it works in bash by running:

```
$ echo "going to tmp"
$ cd /tmp
$ echo "hello, world"
```

then hit `C-p` `C-p` `C-p` `C-o` `C-o` `C-o` (for a grand total of 6 keystrokes) to run those same three commands again.

Here's the description from `BASH(1)`:

```
     operate-and-get-next (C-o)
          Accept  the current  line for  execution and  fetch the
          next line relative to the current line from the history
          for editing.  Any argument is ignored.
```

**Comment by jonathanslenders** [comment]
Hi @mgalgs,

This has been implemented in https://github.com/jonathanslenders/python-prompt-toolkit/commit/719b94cfc73a0e26be530d7779c2e8c4d50845dd .
You can use this example for testing: https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/examples/operate-and-get-next.py

However, right now, it doesn't work in most prompt_toolkit applications yet. The reason for that is that I don't do a good job of keeping the state between consecutive calls of the "prompt()" function. We don't automatically carry the history to the next call, but even if a user does that explicitely, that's not sufficient for this to work. For IPython it works, if they remove the custom binding for Control-O that they have. I'm also planning to make this work for ptpython (where it doesn't work because the flow is different from other applications). I need to fix that.

So, my plan is to rewrite the "prompt_toolkit.shortcuts" module, and create a better API for readline-like applications, that correctly transfers state between multiple prompt-calls. (See https://github.com/jonathanslenders/python-prompt-toolkit/issues/440 ). Then, when this is ready, everyone should start migrating to this API in order to get this functionality.

**Comment by jonathanslenders** [comment]
Closing this, given that it's implemented. Feel free to open again, if something is missing.

**Comment by mgalgs** [comment]
> For IPython it works, if they remove the custom binding for Control-O that they have.

For any future searchers, here's how you can remove IPython's Control-O handler so that you can get this Control-O goodness:

`~/.ipython/profile_default/startup/20-keyboard.py`:

```python
from IPython import get_ipython
from IPython.terminal.shortcuts import newline_with_copy_margin


ip = get_ipython()
registry = ip.pt_cli.application.key_bindings_registry

registry.remove_binding(newline_with_copy_margin)
```

**Comment by randy3k** [comment]
@mgalgs 
excellent tips!!

**Comment by randy3k** [comment]
By the way, in iPython 6, I need
```
from IPython import get_ipython

ip = get_ipython()
registry = ip.pt_cli.application.key_bindings_registry

handler = next(kb.handler for kb in registry.key_bindings if kb.handler.__name__ == "newline_autoindent")
registry.remove_binding(handler)
```

**Comment by mgalgs** [comment]
One more iteration on @randy3k's solution (which I needed to get things working in both python2 and python3):

```python
from IPython import get_ipython

ip = get_ipython()
registry = ip.pt_cli.application.key_bindings_registry

handler = next(kb.handler for kb in registry.key_bindings
               if kb.handler.__name__ in {"newline_autoindent",
                                          "newline_with_copy_margin"})
registry.remove_binding(handler)
```
