### ISSUE TITLE
ControlM detected as ControlJ

### ISSUE THREAD

**Issue by infokiller** [jonathanslenders/python-prompt-toolkit#420]
I'm using Terminator on Linux, and Bash/Zsh successfully differentiate between `Ctrl-J` and `Ctrl-M`. I know that because hitting `Ctrl-V` and then one of these keys prints different things.

When I bind `Ctrl-M` in prompt_toolkit it seems that `Ctrl-J` is also bound to the same action, so I assume that prompt_toolkit doesn't differentiate between them correctly.

Is there a workaround to this issue?

My use case is to map `Ctrl-Enter` to execute the current commands, regardless of the cursor position.

Thanks!

**Comment by jonathanslenders** [comment]
This is a known issue. I'm not able to fix it right now, because it would break some prompt_toolkit based applications, including IPython. However, this needs to be fixed in prompt_toolkit>=1.1.0 or >=2.0.0 something like that.

See: https://github.com/jonathanslenders/python-prompt-toolkit/issues/358 and https://github.com/jonathanslenders/pymux/issues/49

**Comment by infokiller** [comment]
Thanks for the quick response! sounds good, I'll wait for the fix.

**Comment by jonathanslenders** [comment]
This has been fixed in 2.0, so I'm closing this issue.
