### ISSUE TITLE
Is it possible to use python-prompt-toolkit on Android using Kivy?

### ISSUE THREAD

**Issue by caaarlos** [jonathanslenders/python-prompt-toolkit#422]
I'm wondering to known if  it is possible to use python-prompt-toolkit on Android using Kivy. Is it?

**Comment by jonathanslenders** [comment]
@caaarlos: Personally, I have no Kivy experience, so that's hard to tell. If Kivy has a widget that renders a vt100 terminal (I have no idea), then yes, this is possible. If not, then you will have to build a custom rendering backend, but that's not going to be easy and maybe requires changes to prompt_toolkit itself.

**Comment by jonathanslenders** [comment]
Closing this. prompt_toolkit  should work on any vt100 emulator. So, if Kivy doesn't have that, it probably needs to be implemented as part of the Kivy project.
