### ISSUE TITLE
Revert vi-mode behavior to match GNU readline

### ISSUE THREAD

**Issue by ndronen** [jonathanslenders/python-prompt-toolkit#431]
Opening this issue to follow up on the discussion in https://github.com/ipython/ipython/issues/10075.

**Comment by yyt16384** [comment]
I suggest keeping a "readline vi mode" and a "real vi mode" (maybe implemented as an option), as some people prefer vi/vim key bindings.

**Comment by ndronen** [comment]
As a long-term user of the vim editor and the GNU readline vi mode via bash, I know that to search within a single multiline, er, line, withput resorting to Esc-/, I simply enter 'f' in navigation/command mode.  That's how, for instance, I search within a very long one-line shell program in interactive bash.  

That said, I don't know the history of prompt_toolkit outside of my experience with it as a replacement for readline in IPython.  From that perspective, backward compatibility with GNU readline's behavior would be an appropriate vi mode.  On the other hand, prompt_toolkit is used by applications other than IPython, and it is possible that some of them are full-fledged editors.  For those applications, it would make sense for prompt_toolkit's vi mode to behave like the editor, not like readline.

I have no objection to introducing two vi-specific options for enabling the command-line ("vi readline mode") and interactive editor ("vi editor mode") use cases.  If there are compelling objections to having those options, a minimal solution is to include examples in the prompt_toolkit examples directory for vi mode users showing how to set up a prompt for both use cases.

**Comment by jonathanslenders** [comment]
For now, almost all use cases for prompt_toolkit are for reading input, just like GNU readline. So, I follow the reasoning that we should stay as much as possible compatible with readline.

However, this should indeed become an option. (Just to keep searching in Pyvim/pymux in the right direction.)

Thanks for creating the issue!

**Comment by waterbug** [comment]
Is there any kind of work-around for this until it is fixed?  It is definitely impacting my productivity.  Thanks!

**Comment by jonathanslenders** [comment]
Hi everyone, I just pushed a commit that reverses the search direction for Vi mode: https://github.com/jonathanslenders/python-prompt-toolkit/commit/9a79ca172891cf03995d75e044f5663ee3c10e17

It's still slightly different from Readline, because '/' and '?' still enter incremental search instead of non-incremental search. I guess for now that's not too much of an issue, but it's something I need to fix in the future.

Related commit for ptpython: https://github.com/jonathanslenders/ptpython/commit/a451952b71e8b6cc4ece13d0687a65e375075610
IPython follows the new behaviour without any change.
