### ISSUE TITLE
Expose operator() and text_object() in key_binding/bindings/vi.py as public functions

### ISSUE THREAD

**Issue by yyt16384** [jonathanslenders/python-prompt-toolkit#434]
This will make creating custom operators and text objects easier.

**Comment by jonathanslenders** [comment]
Hi @yyt16384 That's true, very good point!
But first, there is some refactoring to the key bindings that I need to do in order to make this possible.

Some notes for myself:
- ``load_vi_bindings`` should not take a ``enable_visual_key`` argument. This should become a property of the ``CommandLineInterface`` class.
- ``load_vi_bindings`` also should not take a ``filter`` argument. So far, there was never a need to enable/disable all key bindings. People can easily override bindings, switch the editing_mode, and so on.
- ``load_vi_bindings`` should also not take a ``get_search_state`` argument. This should probably become an argument of a "UI widget". (For this part, I need to refactor the layout engine. That's the hardest part.)
Then ``load_vi_bindings`` is completely stateless, and adding custom operators or text objects should be easy.

**Comment by jonathanslenders** [comment]
Implemented in https://github.com/jonathanslenders/python-prompt-toolkit/commit/37cb52b2558e9e4a5577b9b01fa2669d8e3540a2

Example usage: https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/examples/custom-vi-operator-and-text-object.py

If this solves your issue. It can be closed.
(Note that it's still not super easy to implement new operators or text objects.)

**Comment by yyt16384** [comment]
It looks good enough to me.
