### ISSUE TITLE
Characters on the same line as the prompt disappear

### ISSUE THREAD

**Issue by Siecje** [jonathanslenders/python-prompt-toolkit#453]
If the output of the previous command doesn't end in a new line the characters on the same line as the prompt will disappear.
https://github.com/xonsh/xonsh/issues/2093

**Comment by jonathanslenders** [comment]
Hi @Siecje,

Thanks for reporting this issue! I understand what's going on, but it's something very difficult to handle.
Ideally, we would be able to write a newline to the screen, if the previous application failed to output one.

However, prompt_toolkit has no way of knowing whether the previous command printed a newline. We could send out a CPR request to determine the cursor position, but terminal CPRs work asynchronously, making the UI feel slow. This would work by printing a CPR to stdout, then the terminal replies with the cursor coordinates on stdin. There we can check the 'x' position of the cursor. Doing this, however, is noticable, due to the delay.

Unlike prompt_toolkit, readline is able to render the prompt at any position, using relative cursor positioning. For simple prompts, that is possible, but the render engine of prompt_toolkit is more complex, it needs to handle multiline inputs in a reliable way, and has some optimizations built-in to improve the render performance. This doesn't work well with relative positioning.

Right now, honestly, I have no idea how to handle this correctly.

**Comment by jonathanslenders** [comment]
Closing this, as it's very unlikely that we can do something about this.
