### ISSUE TITLE
Suggestions how to test a cli application

### ISSUE THREAD

**Issue by asmeurer** [jonathanslenders/python-prompt-toolkit#477]
I'm not too good with pipes and selectors and threads, and I'm hoping you could suggest a solution here. I am trying to write some tests for my application. Basically, I have a main loop that takes the result from a `cli` and has some logic to execute it (it is this logic that I want to test). 

My idea is to do

```py
from prompt_toolkit.output import DummyOutput

class _TestOutput(DummyOutput):
    def __init__(self):
        self.written_data = []

    def write(self, data):
        self.written_data.append(data)

def test_main_loop():
    from prompt_toolkit.shortcuts import create_eventloop
    # This function is based on https://github.com/jonathanslenders/python-prompt-toolkit/blob/4a27a142de525bb5a84edfb7df0bfa673ef9847e/tests/test_cli.py#L30, set to use _TestOutput and not close the eventloop or input
    result, cli = _cli_with_input('1\n', eventloop=create_eventloop(), close=False)

    # This is the function that gets the result from the cli and does the execution logic
    main_loop(cli)
    cli.eventloop.close()
    cli.input.close()
    assert cli.output.written_data == ...
```

The problem here is that this hangs on the `cli.eventloop.close()` call. I've used some signal handlers to raise an exception and found that it is stuck [here](https://github.com/jonathanslenders/python-prompt-toolkit/blob/99fa7fae61c9b4ed9767ead3b4f9b1318cfa875d/prompt_toolkit/eventloop/inputhook.py#L89). 

I am able to "fix" this by doing this:

```py
def test_main_loop():
    from prompt_toolkit.shortcuts import create_eventloop
    import signal
    result, cli = _cli_with_input('1\n', eventloop=create_eventloop(), close=False)
    def handler(s, f): raise KeyboardInterrupt
    signal.signal(signal.SIGALRM, lambda s, f: handler(s, f))
    signal.setitimer(signal.ITIMER_REAL, 1)

    main_loop(cli)
    cli.eventloop.close()
    cli.input.close()
    assert cli.output.written_data == ...
```

But I don't like it, because if I set the timer too low, the test will break, and if I set it too long, the tests will take a long time (I want to have many such tests). 

Do you have any idea how to break the deadlock, so that I can just test the program normally, without any interrupt timers?

It's worth noting that https://github.com/jonathanslenders/python-prompt-toolkit/pull/382 completely breaks this. I can't even keyboard interrupt the tests with that PR (either from a signal handler or from the keyboard), it has to be killed. The fact that that PR breaks the ability to keyboard interrupt when deadlocks happen suggests to me that it is a bad idea, but as I said I'm no expert, so I could be wrong.

**Comment by jonathanslenders** [comment]
Hi @asmeurer,

Great to see that you want to write unit tests.

First thing however, is question yourself what you want to test. Do you really want to compare the data that is written to the output? If so, then you are more testing the rendering algorithm of prompt_toolkit, rather than your own application. The rendering algorithm of prompt_toolkit can change anytime, for instance to provide more efficient rendering, but that doesn't mean that it's visually different, or that it would affect your application.

I do have unit tests that test the CLI as a whole: https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/tests/test_cli.py  You may want to have a look at those, but still, I'm not convinced that it ever makes sense to do this outside of prompt_toolkit.

Usually, the idea of unit testing is to test your own code and replace third-party code by mock objects. If that is possible, than you also have the freedom to replace the dependencies by something else. (Think about the "dependency inversion principle".) So, try to decouple your own code from it's dependencies as much as possible, that way you don't have to run third-party code in order to test your own code.

If you feel that some tests are missing in prompt_toolkit itself, then it could make sense to integrate these tests in the prompt_toolkit code base.

(I'm not exactly sure what's going on with the code that's blocking. Using signals and timers doesn't feel like the right way to go in any case.)

Jonathan

**Comment by asmeurer** [comment]
You're right. I was thinking that I need to test the input and output as one thing, but actually it's sufficient to test them separately, meaning for the input I can test the cli like in prompt_toolkit's test_cli, and for the output I can just pass in the command (basically, not using prompt_toolkit at all). Not sure why I was making it so complicated on myself.
