### ISSUE TITLE
on_text_deleted hook for Buffer

### ISSUE THREAD

**Issue by asmeurer** [jonathanslenders/python-prompt-toolkit#500]
Buffer has on_text_changed and on_text_inserted, but it doesn't have an on_text_deleted hook that fires when text is deleted.

**Comment by jonathanslenders** [comment]
(sorry for the late reply.) This is not feasible, and won't be added. Sorry about that. An assignment of the ``text`` attribute could actually be a deletion, or a whole sequence of modifications. The buffer has no idea of what operations are done because of that assignment. This needs to be triggered in a custom key binding if needed.
What would you do with this hook?

**Comment by asmeurer** [comment]
I would use it to reset my (customized) history search. It looks like I achieved the effect I wanted by overriding `delete_before_cursor` in my custom `Buffer` subclass.

**Comment by jonathanslenders** [comment]
Okay. That would probably be the way to go, if you want certain customization. Closing this, given that this doesn't need to be part of prompt_toolkit itself.

(The main problem is that if I added on_text_deleted, people would start relying on that, which is bad, because we can't guarantee it will be called for every delete operation.)
