### ISSUE TITLE
High CPU usage and slow response

### ISSUE THREAD

**Issue by tibabit** [jonathanslenders/python-prompt-toolkit#516]
Hi,

I was trying to run pyvim on a arm machine with 512 RAM, and I noticed that it is taking too much time. It takes around 8 seconds for it to even start and CPU usage reaches 80-90%. Also when I start typing then again CPU usage reaches 60-90 %.
Is there any reason for this?
Can this be fixed?

**Comment by jonathanslenders** [comment]
Hi @tibabit,

Yes, pyvim does a lot of string operations, both during text editing as during the rendering of the UI.   For ptpython or IPython this isn't that noticable, because the screen area is usually much smaller, but for pyvim this can become noticable on slower systems. Especially an arm machine.

I wanted prompt_toolkit to remain pure Python (without C extensions) if feasible, and so far it worked really well (there are already a crazy amount of optimizations to make it as fast as possible). Writing parts in C would speed things up significantly, but it's not that trivial. Not to maintain, and more difficult to distribute.

I guess I need to to more profiling on my raspberry. At this point there is no obvious solution. Maybe you can try to use Pypy instead of CPython. I guess the startup time won't change, but it could become a lot faster after a short while.

**Comment by tibabit** [comment]
@jonathanslenders thanks
