### ISSUE TITLE
Large buffers in Windows causes rendering errors

### ISSUE THREAD

**Issue by lllama** [jonathanslenders/python-prompt-toolkit#521]
I have a `VSplit` with two `BufferControls`. Unfortunately, on Windows only about half of the screen gets drawn if the right buffer has . If I trim the right buffer to 24 lines then things get drawn as expected but 25 causes the issue. Those numbers increase slightly if I remove the margins from the left split but not enough to get towards the ~2000 lines I'll need to display.

I'll try and put together a minimal example but just lodging this here for now in case this is a known issue.

This is a full screen app btw.

**Comment by jonathanslenders** [comment]
Hi @lllama,

Would it be possible for you to try the 2.0 branch? I see that you're building a custom full screen application. I know it's not released yet, but so many improvements and fixes were done that should make full screen applications easier to build. Check out the full screen examples.
Let me know if that solves  it.

Otherwise, I guess that specifying a width for the BufferControl could help.
Or, if it's too complex, feel free to share the code by mail.

Thanks,
Jonathan

**Comment by lllama** [comment]
Specifying the width seems to have worked (though I just picked an `exact` to play with for the time being).

The version 2.0 stuff looks really interesting but also seems to have changed a lot of the concepts (`BufferMapping` disappearing for one thing). I'll definitely have a play with the examples though and look to port this app over as a test.

Thanks for the quick response - feel free to close this issue.

**Comment by jonathanslenders** [comment]
That's right. For 2.0, I had to change certain APIs, because they didn't fit well for full screen applications. ``BufferMapping`` assumed that the focussed widget is always a buffer. This used to be the case, but in come complex UIs it could be a button, or any custom widget.
Before releasing 2.0, I'm planning to write documentation on how to transition from 1.0 to 2.0 as well.

I'll close this one. Feel free to open a new issue if you have any more questions!
