### ISSUE TITLE
Is it possible to have a "shift + enter" keybinding?

### ISSUE THREAD

**Issue by nhumrich** [jonathanslenders/python-prompt-toolkit#529]
I want to have a text input buffer that accepts the text on normal enter, but does a newline on `Shift` + `Enter`. Kind of like slack. 
I dont see ShiftEnter in the list of keys, and I tried adding a binding for `Key('<ShiftEnter>')` but that didnt seam to work either. 

Is there a way I can intercept shift enter so I can make it do `buffer.newline()`? or is there another way to do this?

**Comment by asmeurer** [comment]
What terminal emulator do you use? Most don't recognize Shift-Enter as separate from Enter, as far as I know. But some let you define custom sequences for different keys. 

I use iTerm2, and in the settings I have it set so that Shift-Enter sends `^[ [ag` (that is, the escape sequence `[ag`). The `ag` part is basically random (I don't know if there's a more appropriate escape sequence for Shift-Enter). 

Then I use

```py
from prompt_toolkit.terminal.vt100_input import ANSI_SEQUENCES
from prompt_toolkit.keys import Keys, Key

Keys.ShiftEnter = Key("<Shift-Enter>")
ANSI_SEQUENCES['\x1b[ag'] = Keys.ShiftEnter
```

I personally use Shift-Enter to force an accept

```py
from prompt_toolkit.key_binding.bindings.named_commands import accept_line

# r is my bindings registry
r.add_binding(Keys.ShiftEnter)(accept_line)
```

**Comment by nhumrich** [comment]
Hmm.. i personally use Konsole.
But i would want this to work on all terminals ideally. Your saying there is no easy way?

**Comment by asmeurer** [comment]
I don't think so. If you press Shift-Enter, the terminal sees that as the same as Enter, unless you configure it otherwise.

**Comment by jonathanslenders** [comment]
Indeed, most terminals don't support it by default.
The Windows console does it, on the other hand.

**Comment by nhumrich** [comment]
Well thats a bummer. Thanks for the info!

**Comment by asmeurer** [comment]
So you don't actually have to add things to `Keys` (it's just a str Enum). However, to be valid, a key needs to be a single character. What you can use as a workaround is to set the key to a single Unicode character (it doesn't matter which, I use `ShiftEnter = '⌤'`), then add that to the `ANSI_SEQUENCES` dictionary.
