### ISSUE TITLE
2.0 fails on python 2: keybindings need to be text_type

### ISSUE THREAD

**Issue by randy3k** [jonathanslenders/python-prompt-toolkit#539]
There are couple of places comparing string to `text_type`
```
assert isinstance(key, text_type)
```
and they fail.

Should `text_type` be `string_types`?

**Comment by jonathanslenders** [comment]
This is actually on purpose, it was like that on 1.0 already.
For Python 2, you have to pass a ``unicode`` object, not a ``str`` object.

**Comment by randy3k** [comment]
Even for keybindings?
```
    @kb.add('c-c')
  File "rice/deps/prompt_toolkit/key_binding/key_bindings.py", line 160, in add
    keys = tuple(_check_and_expand_key(k) for k in keys)
  File "rice/deps/prompt_toolkit/key_binding/key_bindings.py", line 160, in <genexpr>
    keys = tuple(_check_and_expand_key(k) for k in keys)
  File "rice/deps/prompt_toolkit/key_binding/key_bindings.py", line 304, in _check_and_expand_key
    assert isinstance(key, text_type)
```

**Comment by jonathanslenders** [comment]
Yes, even there. The input, which we read from stdin is decoded right after reading, before it's passed into the state machine that processes the key bindings. If we would compare ``unicode`` against ``str`` over there, that could cause a lot of bugs. That's why I recommend to use ``from __future__ import unicode_literals`` on Python 2. Django does the same thing.

**Comment by randy3k** [comment]
Thanks for the advice.
