### ISSUE TITLE
No color prompt on macOS with `true_color = True`

### ISSUE THREAD

**Issue by thorstenkampe** [jonathanslenders/python-prompt-toolkit#546]
On macOS coloring the prompt does not work when using `true_color = True` (using macOS' standard Terminal).

Minimal code:
```python
import prompt_toolkit as pt, pygments

def prompt_tokens(cli):
    return [(pygments.token.Token.Prompt, 'prompt')]

pt.prompt(get_prompt_tokens = prompt_tokens,
          style             = pt.styles.style_from_dict({pygments.token.Token.Prompt: '#00FFFF'}),
          true_color        = True)
```

**Comment by thorstenkampe** [comment]
`$TERM` is `xterm-256` on macOS. Is it possible that `true_color` reverts to "no color" if the terminal does not support true colors (more than 256 colors).

On the other hand I'm pretty sure that Windows cmd does not support more than 256 colors. And it shows the prompt colored with `true_color = True`.

**Comment by jonathanslenders** [comment]
Hi @thorstenkampe,

There is no standardized way for applications to detect when true color is supported. This is why prompt_toolkit takes it as a boolean input, which is supposed to be configured somewhere by the user.

When this flag is set, prompt_toolkit will output true color escape sequences, instead of the indexed colors. Terminals that don't understand these will typically ingore them, which is what happens in your case.

Windows supports usually only 16 colors. Windows 10 however supports true color vt100 escape sequences after the latest update. This is supported by the (unreleased) 2.0 branch of prompt_toolkit, but not by 1.0.
