### ISSUE TITLE
Tab not displayed properly

### ISSUE THREAD

**Issue by Woile** [jonathanslenders/python-prompt-toolkit#556]
Hi guys, I'm trying to add a tab `\t` to the prompt but it doesn't seem to work. I might be missing something here, is there a way to solve this? 

```python
In [3]: prompt('foo\t\tbar')
foo^I^Ibar
```
I've also tried the unicode representation:
```python
In [13]: prompt('foo\u0009bar')
foo^Ibar
```

On the other hand `\n` works fine
```python
In [11]: prompt('foo\nbar')
foo
bar
```

Sorry if it's something silly, I've been searching in google and reading the docs and I cannot find anything.

Thanks a lot!

**Comment by jonathanslenders** [comment]
Hi @Woile,

Excuse me for the late reply. I just got married, and I've been offline for a while.

This is not really supported yet. For the input itself, it works, because the TabsProcessor is handling that:
https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/prompt_toolkit/layout/processors.py#L489
For the prompt, there is no such thing (yet). Right now, it's best to calculate the amount of spaces and replace the tabs in the prompt. I hope that works.

**Comment by Woile** [comment]
Congratulations @jonathanslenders ! 

I'll try calculating tabs, let's see if it's possible.
Regards!

**Comment by jonathanslenders** [comment]
Closing this, assuming it's possible by replacing the tabs with spaces. Let me know if that doesn't work.
