### ISSUE TITLE
ANSI_COLOR_NAMES naming

### ISSUE THREAD

**Issue by mkoskar** [jonathanslenders/python-prompt-toolkit#559]
It seems to me that the naming is wrong. Mainly, why are "high intensity" colors named as "dark"?

Current:
```
ANSI_COLOR_NAMES = [
    'ansiblack', 'ansiwhite', 'ansidefault',

    # Low intensity.
    'ansired', 'ansigreen', 'ansiyellow', 'ansiblue', 'ansifuchsia', 'ansiturquoise', 'ansilightgray',

    # High intensity. (Not supported everywhere.)
    'ansidarkgray', 'ansidarkred', 'ansidarkgreen', 'ansibrown', 'ansidarkblue',
    'ansipurple', 'ansiteal',
]
```

1) Why not using well-known (https://en.wikipedia.org/wiki/ANSI_escape_code#Colors) naming like (`red`, `brightred`, etc.)?

2) Is `ansi` prefix necessary?

3) There are `0-15` (that is 16 ANSI colors), and then `default`, but list above has 18 elements.

**Comment by jonathanslenders** [comment]
I agree. There was some confusion around this.
Right now it's consistent with the Pygments code, but I'm in favour of fixing it in 2.0 (maybe with some compatibility towards Pygments styles.) See: https://bitbucket.org/birkenfeld/pygments-main/src/7941677dc77d4f2bf0bbd6140ade85a9454b8b80/pygments/style.py?at=default&fileviewer=file-view-default

The ANSI prefix however is necessary, because prompt_toolkit also supports all these named colors: https://github.com/jonathanslenders/python-prompt-toolkit/blob/2.0/prompt_toolkit/styles/named_colors.py The ANSI colors map to the ANSI colors of the terminal, while the named colors use whatever color from the 256 (or full) colors is closest.

cc: @Carreau

**Comment by jonathanslenders** [comment]
Fixed here: https://github.com/jonathanslenders/python-prompt-toolkit/commit/6fbe54116b90eb2559b00c427d89b593cb836d41
