### ISSUE TITLE
Add "ptrepl - Run command as REPL" to README

### ISSUE THREAD

**Issue by imomaliev** [jonathanslenders/python-prompt-toolkit#584]
Hi, I would like to add my project https://github.com/imomaliev/ptrepl to README.

It is still WIP, but already ready to use.

**Comment by jonathanslenders** [comment]
Sure, can you make a pull request?

**Comment by imomaliev** [comment]
@jonathanslenders Sure, #586

**Comment by imomaliev** [comment]
@jonathanslenders Btw, I wanted to thank you for this awesome project! And also ask, do you know any python libraries for bash like history manipulation, and PS1 parsing, because currently for my project I had to write them myself.

**Comment by jonathanslenders** [comment]
Hi @imomaliev, thanks!

For PS1 prompt parsing, check either Pyte or this function: https://github.com/jonathanslenders/python-prompt-toolkit/blob/2.0/prompt_toolkit/formatted_text.py#L293
It's not really easy, because a PS1 prompt can be any sequence of VT100 escapes.

For bash like history completion, I'm not exactly sure what you mean.

**Comment by imomaliev** [comment]
@jonathanslenders I meant history expansion http://structure.usc.edu/bash/bashref_9.html#SEC115.
Also I think you would be interested to know about this project - https://github.com/xonsh/py-bash-completion python interface for bash completion which is used in xonsh.

**Comment by jonathanslenders** [comment]
Hi @imomaliev,
History expension like Bash is not supported by prompt_toolkit yet. However, it can probably build on top by creating a custom Completer object. Thanks for the link to Xonsh.

**Comment by imomaliev** [comment]
@jonathanslenders Understood, thanks!
