### ISSUE TITLE
No input in Win10 Asyncio

### ISSUE THREAD

**Issue by sander76** [jonathanslenders/python-prompt-toolkit#585]
See code below.
I get the prompt. But I cannot enter any test into it...

```
import asyncio
from prompt_toolkit import prompt
from prompt_toolkit.patch_stdout import patch_stdout


async def my_coroutine():
    while True:
        with patch_stdout():
            result = await prompt('Say something: ', async_=True)
        print('You said: %s' % result)


if __name__ == "__main__":
    loop = asyncio.get_event_loop()
    loop.run_until_complete(my_coroutine())
```

**Comment by jonathanslenders** [comment]
Thanks for noticing this! The code looks fine and I can reproduce this issue. I'll have a look.

**Comment by jonathanslenders** [comment]
Hi @sander76,

The problem here was that prompt_toolkit didn't know it had to use the asyncio event loop. It was still using the internal loop which wasn't running.

Try calling ``use_asyncio_event_loop()`` at the start of your application, like here:
https://github.com/jonathanslenders/python-prompt-toolkit/blob/2.0/examples/prompts/asyncio-prompt.py#L61

Does that work?

**Comment by sander76** [comment]
👍
