### ISSUE TITLE
Question: Displaying ANSI colored text in TextArea/Widgets

### ISSUE THREAD

**Issue by rajaravivarma-r** [jonathanslenders/python-prompt-toolkit#616]
Is there a way to display ANSI colored text in TextArea or any other *output* widget? All the examples I am able to see are for displaying colored text in Prompt, but not in TextArea or in any other widget.

All the colored-text related example uses `print_formatted_text`, but not shows how to display ANSI escaped strings in any of the widgets.

I have been trying to create something like *fzf* but very minimal. It would be great, if someone chime in and help. Thanks.

**Comment by jonathanslenders** [comment]
Hi @rajaravivarma-r,

I'm not entirely sure whether this question is about prompt_toolkit 1.0 (the version on Pypi) or 2.0 (master branch). For what you're building I think in any case, 2.0 works better.

Colored text can be displayed in any widget that uses a ``FormattedTextControl`` underneath.
``TextArea`` on the other hand, derives from ``BufferControl``, which displays an input text. In order to highlight this, you have to use a ``Lexer``, which transforms the input text into a list of ``(style,text)`` tuples.

So, f you want the user to be able to navigate through ANSI colored text, then indeed you can use a ``TextArea``, store the plain text in the text area, and return the ANSI colored text from within the lexer (this is line by line). Probably, you'll have to dive a bit through the code, to make this work.

pypager (https://github.com/jonathanslenders/pypager) is an application that uses this technique to display the colored output of commands like "man" in a ``BufferControl``.

**Comment by rajaravivarma-r** [comment]
@jonathanslenders Thanks. I was talking about version 2.0 indeed.

I will check the *pypager* implementation and see if I can work it out from there.

Also, is there any place in the documentation which tells you what widgets use *FormattedTextControl* and what widgets use *BufferControl*? Or should I look for `Widget` classes inheriting from `FormattedTextControl`.

Thanks again.

**Comment by jonathanslenders** [comment]
Anything that requires text input (with all editing functionality) uses a ``BufferControl``. It can also be used for read-only text that still requires navigation key bindings like cursor movement and page up/down.

Any text that is static, not focusable, uses typically ``FormattedTextControl``.

The highlighting works different. In the first case, this is done by a lexer. In the second case, you can pass formatted text directly.

**Comment by rajaravivarma-r** [comment]
Great, it will make more sense now when reading the source. Thank you.
