### ISSUE TITLE
TextArea widget parameter accept_handler does not pass buffer to callback

### ISSUE THREAD

**Issue by Arrowbox** [jonathanslenders/python-prompt-toolkit#645]
The parameter `accept_handler` is used during `TextArea.__init__()` with a lambda:

```
accept_handler=lambda buff: accept_handler and accept_handler())
```
I expected this to behave the same as the `accept_handler` parameter in the `Buffer` class and take the buffer as one of the arguments. However, the lambda above does not forward the buffer argument so the handler does not receive a copy of the buffer. Is this expected?

**Comment by jonathanslenders** [comment]
Hi @Arrowbox,

Good point. First, the main idea of ``TextArea`` was to abstract away all the underlying details of ``Buffer/Window/BufferControl``, but I think this makes sense indeed. For consistency and because in that handler you need access to the text anyway.

Feel free to create a pull request for this. I know it's backwards-incompatible, but the ``widgets`` API is not set in stone yet, and is allowed to change. (Do git-pull first, I already did a recent change here.)

**Comment by Arrowbox** [comment]
I've made a PR #650 with the changes including the shortcuts and example updates.

**Comment by jonathanslenders** [comment]
Closing this,  https://github.com/jonathanslenders/python-prompt-toolkit/pull/650 has been merged.
