### ISSUE TITLE
Inverted style causes problems

### ISSUE THREAD

**Issue by techtonik** [jonathanslenders/python-prompt-toolkit#660]
This doesn't work as expected:
```
def bottom_toolbar():
    return FormattedText([
        ("fg:white bg:black", "F1 Help"),
    ])
```
Produces:
![image](https://user-images.githubusercontent.com/515889/42138795-63079220-7dad-11e8-8b98-b1d401b6047c.png)

I thought FormattedText should somehow validate the params.

**Comment by techtonik** [comment]
Looks like params are understood, but are inverted.

**Comment by jonathanslenders** [comment]
Hi @techtonik,

Yes, this is because the "reverse" flag is set for the ``bottom-toolbar`` style. See: https://github.com/jonathanslenders/python-prompt-toolkit/blob/a4a010e4e4bf08755ed1efd587de34843cfe2f07/prompt_toolkit/styles/defaults.py#L129

You can override this by passing a style that doesn't use reverse here:
```python
style = Style.from_dict({'bottom-toolbar': 'noreverse'});
```

The reason we use reverse here is because it works well for terminals with both a light and dark background.

**Comment by techtonik** [comment]
OMG. Spent so much time on this issue. But now I know this software better. =)

**Comment by techtonik** [comment]
I think documented this behavior is enough to close this issue. Need to look for a place to document `bottom_toolbar` and explain that it is a widget with style and behavior that anybody can create. Maybe a tutorial how to create such bar from scratch could be useful. Then people can compare with existing.

**Comment by techtonik** [comment]
Actually, it is documented here http://python-prompt-toolkit.readthedocs.io/en/stable/pages/asking_for_input.html#adding-a-bottom-toolbar but I missed that.
