### ISSUE TITLE
Print layout

### ISSUE THREAD

**Issue by njalerikson** [jonathanslenders/python-prompt-toolkit#737]
Would it be possible to modify `print_formatted_text` so we can pass a `Layout`/`Container` to display?

I'm digging through the `Renderer` object and trying to decide how large of a change this would be.

**Comment by jonathanslenders** [comment]
Hi @njalerikson,

Excuse me for the late reply! I've addad a ``print_container`` utility. (``print_layout`` is not needed, I think, because if it's only for printing, we don't care about the focus.)

See this commit: https://github.com/jonathanslenders/python-prompt-toolkit/commit/af1cd758d4eac9a7f64cb833499b4b80ec001a89

Example usage:
```python
from prompt_toolkit.shortcuts import print_container
from prompt_toolkit.widgets import Frame, TextArea

print_container(
    Frame(TextArea(text='Hello world!')))
```

See also: https://github.com/jonathanslenders/python-prompt-toolkit/issues/730
